#! /bin/sh

export PATH="/home/nik/.local/bin:$PATH"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           4

bspc config split_ratio          0.70
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^10' follow=off
bspc rule -a Chromium-browser desktop='^9' follow=off
bspc rule -a transmission-gtk desktop='^8' follow=off

dunst &

# xrandr --output eDP --brightness 0.2
wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.9

feh --bg-scale --randomize /home/nik/pics/wall/*


if [ ! -e /tmp/startup_completed ]; then
    
    # flatpak run org.telegram.desktop &
    # sleep 0.5
    # flatpak run com.github.Eloston.UngoogledChromium &
    # sleep 0.5
    # flatpak run com.transmissionbt.Transmission &
    # sleep 0.5
    firefox &
    sleep 0.5
    touch /tmp/startup_completed
fi

sleep 1
setxkbmap -option ctrl:ralt_rctrl

sleep 1
batterynotify &
